import { Role, ModuleId, RoleInfo, Member, AuditLog, SystemModule, PersonnelType, AccessRequest } from "./types";

export const ROLE_CONFIG: Record<Role, RoleInfo> = {
  admin: {
    id: "admin",
    label: "ผู้ดูแลระบบ (Admin)",
    badgeColor: "bg-indigo-100 text-[#4F46E5] border-indigo-200",
    description: "มีสิทธิ์สูงสุด เข้าถึงได้ทุกโมดูล จัดการสมาชิก และกำหนดนโยบายความปลอดภัย",
    icon: "👑",
  },
  manager: {
    id: "manager",
    label: "ผู้จัดการ (Manager)",
    badgeColor: "bg-teal-100 text-[#0D9488] border-teal-200",
    description: "จัดการงานทีม ตรวจสอบรายงาน อนุมัติการใช้ทรัพยากร แต่ไม่สามารถจัดการสิทธิ์ระบบได้",
    icon: "👔",
  },
  member: {
    id: "member",
    label: "พนักงาน (Member)",
    badgeColor: "bg-blue-100 text-blue-700 border-blue-200",
    description: "เข้าถึงงานส่วนตัว แชทกลุ่ม การประชุม และจองรถยนต์สำนักงานได้ตามสิทธิ์",
    icon: "👤",
  },
  guest: {
    id: "guest",
    label: "ผู้เยี่ยมชม (Guest)",
    badgeColor: "bg-amber-100 text-amber-800 border-amber-200",
    description: "เข้าถึงได้เฉพาะการประชุมที่ได้รับเชิญและห้องแชทสาธารณะเท่านั้น",
    icon: "🎟️",
  },
};

export const MODULE_NAMES: Record<ModuleId, { name: string; icon: string; desc: string }> = {
  dashboard: { name: "หน้าแรก (Dashboard)", icon: "📊", desc: "ภาพรวมสำนักงาน สถิติ และงานเร่งด่วน" },
  chat: { name: "แชททีม (Chat)", icon: "💬", desc: "การสื่อสารระหว่างสมาชิกและห้องแชทองค์กร" },
  task: { name: "งานและโปรเจกต์ (Tasks)", icon: "📋", desc: "กระดานติดตามงานแบบ Kanban" },
  meetings: { name: "การประชุม (Meetings)", icon: "📹", desc: "ตารางประชุมและห้องสนทนาออนไลน์" },
  carbooking: { name: "รถยนต์สำนักงาน (Car Booking)", icon: "🚗", desc: "ระบบจองยานพาหนะส่วนกลาง" },
  user: { name: "ข้อมูลส่วนตัว (Profile)", icon: "👤", desc: "ข้อมูลผู้ใช้และการตั้งค่าส่วนบุคคล" },
  admin: { name: "ระบบจัดการ (Admin Panel)", icon: "⚙️", desc: "การจัดการสมาชิกและกำหนดสิทธิ์ RBAC" },
  reports: { name: "รายงานและสถิติ (Reports)", icon: "📈", desc: "รายงานสถิติการใช้งานและดาวน์โหลดสรุป" },
};

export const INITIAL_SYSTEM_MODULES: Record<ModuleId, SystemModule> = {
  dashboard: {
    id: "dashboard",
    name: "หน้าแรก (Dashboard)",
    icon: "📊",
    desc: "ภาพรวมสำนักงาน สถิติ และงานเร่งด่วน",
    enabled: true,
    maintenanceNotice: "ระบบภาพรวมสำนักงานเปิดให้บริการปกติ",
  },
  chat: {
    id: "chat",
    name: "แชททีม (Chat)",
    icon: "💬",
    desc: "การสื่อสารระหว่างสมาชิกและห้องแชทองค์กร",
    enabled: true,
    maintenanceNotice: "ระบบแชททีมเปิดให้บริการปกติ",
  },
  task: {
    id: "task",
    name: "งานและโปรเจกต์ (Tasks)",
    icon: "📋",
    desc: "กระดานติดตามงานแบบ Kanban",
    enabled: true,
    maintenanceNotice: "ระบบติดตามงาน Kanban เปิดให้บริการปกติ",
  },
  meetings: {
    id: "meetings",
    name: "การประชุม (Meetings)",
    icon: "📹",
    desc: "ตารางประชุมและห้องสนทนาออนไลน์",
    enabled: true,
    maintenanceNotice: "ระบบนัดหมายการประชุมเปิดให้บริการปกติ",
  },
  carbooking: {
    id: "carbooking",
    name: "รถยนต์สำนักงาน (Car Booking)",
    icon: "🚗",
    desc: "ระบบจองยานพาหนะส่วนกลาง",
    enabled: true,
    maintenanceNotice: "ระบบจองยานพาหนะส่วนกลางเปิดให้บริการปกติ",
  },
  reports: {
    id: "reports",
    name: "รายงานและสถิติ (Reports)",
    icon: "📈",
    desc: "รายงานสถิติการใช้งานและดาวน์โหลดสรุป",
    enabled: true,
    maintenanceNotice: "ระบบจัดทำรายงานและสรุปสถิติเปิดให้บริการปกติ",
  },
  admin: {
    id: "admin",
    name: "ระบบจัดการ (Admin Panel)",
    icon: "⚙️",
    desc: "การจัดการสมาชิกและกำหนดสิทธิ์ RBAC",
    enabled: true,
    maintenanceNotice: "ศูนย์กลางควบคุมระบบและกำหนดสิทธิ์เปิดให้บริการปกติ",
  },
  user: {
    id: "user",
    name: "ข้อมูลส่วนตัว (Profile)",
    icon: "👤",
    desc: "ข้อมูลผู้ใช้และการตั้งค่าส่วนบุคคล",
    enabled: true,
    maintenanceNotice: "ระบบข้อมูลส่วนตัวเปิดให้บริการปกติ",
  },
};

// Default Matrix: Which role can access which module
export const INITIAL_ROLE_PERMISSIONS: Record<Role, Record<ModuleId, boolean>> = {
  admin: {
    dashboard: true,
    chat: true,
    task: true,
    meetings: true,
    carbooking: true,
    user: true,
    admin: true,
    reports: true,
  },
  manager: {
    dashboard: true,
    chat: true,
    task: true,
    meetings: true,
    carbooking: true,
    user: true,
    admin: false, // Managers cannot access RBAC Admin Panel
    reports: true,
  },
  member: {
    dashboard: true,
    chat: true,
    task: true,
    meetings: true,
    carbooking: true,
    user: true,
    admin: false, // Regular members cannot access Admin
    reports: false, // Regular members cannot view company reports
  },
  guest: {
    dashboard: false, // Guests cannot view internal dashboard
    chat: true, // Can chat in public channels
    task: false, // Cannot access internal tasks
    meetings: true, // Can join invited meetings
    carbooking: false, // Cannot book company cars
    user: true, // Can view own profile
    admin: false,
    reports: false,
  },
};

export const GOVERNMENT_PERSONNEL_TYPES = [
  "ข้าราชการ",
  "ลูกจ้างประจำ",
  "พนักงานราชการ",
  "พนักงานกองทุน",
  "พนักงานจ้างเหมาบริการ",
  "ที่ปรึกษา/ผู้ทรงคุณวุฒิ",
] as const;

export const PERSONNEL_TYPE_CONFIG: Record<
  PersonnelType,
  { label: string; badgeColor: string; icon: string; desc: string }
> = {
  ข้าราชการ: {
    label: "ข้าราชการ",
    badgeColor: "bg-blue-50 text-blue-700 border-blue-200",
    icon: "🏛️",
    desc: "ข้าราชการพลเรือนสามัญ บรรจุตาม พ.ร.บ.ระเบียบข้าราชการพลเรือน",
  },
  ลูกจ้างประจำ: {
    label: "ลูกจ้างประจำ",
    badgeColor: "bg-emerald-50 text-emerald-700 border-emerald-200",
    icon: "🛠️",
    desc: "ลูกจ้างประจำส่วนราชการ บรรจุตามระเบียบกระทรวงการคลัง",
  },
  พนักงานราชการ: {
    label: "พนักงานราชการ",
    badgeColor: "bg-teal-50 text-teal-700 border-teal-200",
    icon: "📋",
    desc: "พนักงานราชการตามระเบียบสำนักนายกรัฐมนตรี",
  },
  พนักงานกองทุน: {
    label: "พนักงานกองทุน",
    badgeColor: "bg-purple-50 text-purple-700 border-purple-200",
    icon: "💰",
    desc: "พนักงานกองทุนเฉพาะด้าน (กองทุนคนพิการ/กองทุนคุ้มครองเด็ก/กองทุนผู้สูงอายุ)",
  },
  พนักงานจ้างเหมาบริการ: {
    label: "พนักงานจ้างเหมาบริการ",
    badgeColor: "bg-amber-50 text-amber-800 border-amber-200",
    icon: "🤝",
    desc: "ผู้ปฏิบัติงานตามสัญญาจ้างเหมาบริการรายปี",
  },
  "ที่ปรึกษา/ผู้ทรงคุณวุฒิ": {
    label: "ที่ปรึกษา/ผู้ทรงคุณวุฒิ",
    badgeColor: "bg-indigo-50 text-indigo-700 border-indigo-200",
    icon: "🎓",
    desc: "ผู้ทรงคุณวุฒิ คณะอนุกรรมการ และที่ปรึกษาภาคประชาสังคม",
  },
};

export const GOVERNMENT_DIVISIONS = [
  "สำนักงานพัฒนาสังคมและความมั่นคงของมนุษย์จังหวัดกำแพงเพชร (ผู้บริหาร)",
  "ฝ่ายบริหารทั่วไป",
  "กลุ่มนโยบายและวิชาการ",
  "กลุ่มการพัฒนาสังคมและสวัสดิการ",
  "ศูนย์บริการคนพิการจังหวัดกำแพงเพชร",
  "คณะทำงานที่ปรึกษาและภาคีเครือข่ายภายนอก",
] as const;

export const INITIAL_MEMBERS: Member[] = [
  {
    id: "usr_1",
    prefix: "นางสาว",
    firstName: "มะลิวัน",
    lastName: "สิทธิโยธี",
    name: "นางสาวมะลิวัน สิทธิโยธี",
    nickname: "มิ",
    personnelType: "ข้าราชการ",
    position: "พัฒนาสังคมและความมั่นคงของมนุษย์จังหวัดกำแพงเพชร",
    division: "สำนักงานพัฒนาสังคมและความมั่นคงของมนุษย์จังหวัดกำแพงเพชร (ผู้บริหาร)",
    department: "สำนักงานพัฒนาสังคมและความมั่นคงของมนุษย์จังหวัดกำแพงเพชร (ผู้บริหาร)",
    email: "maliwan.s@m-society.go.th",
    phone: "055-705031 ต่อ 101",
    lineId: "maliwan_kpp",
    role: "admin",
    status: "active",
    joinedDate: "1 ม.ค. 2024",
    avatarText: "มส",
    avatarUrl: "https://kamphaengphet.m-society.go.th/wp-content/uploads/2024/10/S__2457668.jpg",
  },
  {
    id: "usr_2",
    prefix: "นาย",
    firstName: "เสกพล",
    lastName: "ดิษฐโชติ",
    name: "นายเสกพล ดิษฐโชติ",
    nickname: "เสก",
    personnelType: "ข้าราชการ",
    position: "นักพัฒนาสังคมชำนาญการ (หัวหน้าฝ่ายบริหารทั่วไป)",
    division: "ฝ่ายบริหารทั่วไป",
    department: "ฝ่ายบริหารทั่วไป",
    email: "sekpol.d@m-society.go.th",
    phone: "055-705031 ต่อ 102",
    lineId: "sek_kpp",
    role: "manager",
    status: "active",
    joinedDate: "1 ก.พ. 2024",
    avatarText: "สด",
    avatarUrl: "https://kamphaengphet.m-society.go.th/wp-content/uploads/2024/12/2b6d8e58-bfd5-44a7-a18d-4fb8e685452f-e1734057934925.png",
  },
  {
    id: "usr_3",
    prefix: "นาย",
    firstName: "วรวุฒิ",
    lastName: "พึ่งพัก",
    name: "นายวรวุฒิ พึ่งพัก",
    nickname: "เจมส์",
    personnelType: "ข้าราชการ",
    position: "นักพัฒนาสังคมชำนาญการพิเศษ (หัวหน้ากลุ่มการพัฒนาสังคมและสวัสดิการ)",
    division: "กลุ่มการพัฒนาสังคมและสวัสดิการ",
    department: "กลุ่มการพัฒนาสังคมและสวัสดิการ",
    email: "worawut.p@m-society.go.th",
    phone: "055-705031 ต่อ 104",
    lineId: "james_kpp",
    role: "manager",
    status: "active",
    joinedDate: "15 ก.พ. 2024",
    avatarText: "วพ",
    avatarUrl: "https://kamphaengphet.m-society.go.th/wp-content/uploads/2024/11/e735d8a3-9afc-4271-803e-0438ae7cb5371-1-1-e1731912123637.png",
  },
  {
    id: "usr_4",
    prefix: "นาย",
    firstName: "พนมศักย์",
    lastName: "บริภัทรจิรากร",
    name: "นายพนมศักย์ บริภัทรจิรากร",
    nickname: "บอย",
    personnelType: "ข้าราชการ",
    position: "นักพัฒนาสังคมชำนาญการ (รักษาการหัวหน้ากลุ่มนโยบายและวิชาการ)",
    division: "กลุ่มนโยบายและวิชาการ",
    department: "กลุ่มนโยบายและวิชาการ",
    email: "phanomsak.b@m-society.go.th",
    phone: "055-705031 ต่อ 103",
    lineId: "boy_kpp",
    role: "manager",
    status: "active",
    joinedDate: "1 มี.ค. 2024",
    avatarText: "พบ",
    avatarUrl: "https://kamphaengphet.m-society.go.th/wp-content/uploads/2024/11/%E0%B8%9E%E0%B8%B5%E0%B9%88%E0%B8%94%E0%B8%B2%E0%B8%A7-1-1-e1734061864108.png",
  },
  {
    id: "usr_5",
    prefix: "นางสาว",
    firstName: "ขวัญนภา",
    lastName: "ศิริสมบัติ",
    name: "นางสาวขวัญนภา ศิริสมบัติ",
    nickname: "ขวัญ",
    personnelType: "พนักงานราชการ",
    position: "เจ้าหน้าที่ระบบงานคอมพิวเตอร์",
    division: "กลุ่มนโยบายและวิชาการ",
    department: "กลุ่มนโยบายและวิชาการ",
    email: "kwannapa.s@m-society.go.th",
    phone: "055-705031 ต่อ 106",
    lineId: "kwan_kpp",
    role: "member",
    status: "active",
    joinedDate: "10 เม.ย. 2024",
    avatarText: "ขศ",
    avatarUrl: "https://kamphaengphet.m-society.go.th/wp-content/uploads/2024/11/a864cd1c-9230-490f-b838-5f62aa24bfca-e1732079225217.png",
  },
  {
    id: "usr_6",
    prefix: "นางสาว",
    firstName: "สุมาลี",
    lastName: "แสงแก้ว",
    name: "นางสาวสุมาลี แสงแก้ว",
    nickname: "ส้ม",
    personnelType: "พนักงานกองทุน",
    position: "นักสังคมสงเคราะห์ (เจ้าหน้าที่กองทุนส่งเสริมและพัฒนาคุณภาพชีวิตคนพิการ)",
    division: "ศูนย์บริการคนพิการจังหวัดกำแพงเพชร",
    department: "ศูนย์บริการคนพิการจังหวัดกำแพงเพชร",
    email: "sumalee.s@m-society.go.th",
    phone: "055-705031 ต่อ 107",
    lineId: "som_kpp",
    role: "member",
    status: "active",
    joinedDate: "1 พ.ค. 2024",
    avatarText: "สส",
    avatarUrl: "https://kamphaengphet.m-society.go.th/wp-content/uploads/2024/11/e69828cb-560e-4c87-a197-91e98179257a-e1732768762731.png",
  },
  {
    id: "usr_7",
    prefix: "นางสาว",
    firstName: "พิชชาภา",
    lastName: "ห้าวหาญ",
    name: "นางสาวพิชชาภา ห้าวหาญ",
    nickname: "ญาญ่า",
    personnelType: "ข้าราชการ",
    position: "นักสังคมสงเคราะห์ปฏิบัติการ",
    division: "กลุ่มการพัฒนาสังคมและสวัสดิการ",
    department: "กลุ่มการพัฒนาสังคมและสวัสดิการ",
    email: "pitchapa.h@m-society.go.th",
    phone: "055-705031 ต่อ 108",
    lineId: "yaya_kpp",
    role: "member",
    status: "active",
    joinedDate: "1 มิ.ย. 2024",
    avatarText: "พห",
    avatarUrl: "https://kamphaengphet.m-society.go.th/wp-content/uploads/2024/12/88a864d8-a374-4867-87c8-4daa2671153e-e1734057993409.png",
  },
  {
    id: "usr_8",
    prefix: "นางสาว",
    firstName: "อารีวรรณ",
    lastName: "ประเสริฐอุดมศักดิ์",
    name: "นางสาวอารีวรรณ ประเสริฐอุดมศักดิ์",
    nickname: "ดาว",
    personnelType: "ข้าราชการ",
    position: "เจ้าพนักงานการเงินและบัญชีชำนาญงาน (การเงินและบัญชี)",
    division: "ฝ่ายบริหารทั่วไป",
    department: "ฝ่ายบริหารทั่วไป",
    email: "areewan.p@m-society.go.th",
    phone: "055-705031 ต่อ 109",
    lineId: "dao_kpp",
    role: "member",
    status: "active",
    joinedDate: "15 ก.ค. 2024",
    avatarText: "อด",
    avatarUrl: "https://kamphaengphet.m-society.go.th/wp-content/uploads/2024/11/%E0%B8%9E%E0%B8%99%E0%B8%A1%E0%B8%A8%E0%B8%B1%E0%B8%81%E0%B8%A2%E0%B9%8C-%E0%B8%9A%E0%B8%A3%E0%B8%B4%E0%B8%A0%E0%B8%B1%E0%B8%97%E0%B8%A3%E0%B8%88%E0%B8%B4%E0%B8%A3%E0%B8%B2%E0%B8%81%E0%B8%A3-1-e1734061426233.png",
  },
  {
    id: "usr_9",
    prefix: "นาย",
    firstName: "สมหมาย",
    lastName: "มั่นคง",
    name: "นายสมหมาย มั่นคง",
    nickname: "หมาย",
    personnelType: "ลูกจ้างประจำ",
    position: "พนักงานขับรถยนต์ ชำนาญงาน (งานยานพาหนะ)",
    division: "ฝ่ายบริหารทั่วไป",
    department: "ฝ่ายบริหารทั่วไป",
    email: "sommai.m@m-society.go.th",
    phone: "055-705031 ต่อ 110",
    lineId: "sommai_van",
    role: "member",
    status: "active",
    joinedDate: "1 ม.ค. 2022",
    avatarText: "สม",
  },
  {
    id: "usr_10",
    prefix: "นาย",
    firstName: "ธีรพัฒน์",
    lastName: "บุญยืน",
    name: "นายธีรพัฒน์ บุญยืน",
    nickname: "อาร์ม",
    personnelType: "พนักงานจ้างเหมาบริการ",
    position: "เจ้าหน้าที่สนับสนุนงานสารบรรณและเทคโนโลยีดิจิทัล",
    division: "ฝ่ายบริหารทั่วไป",
    department: "ฝ่ายบริหารทั่วไป",
    email: "theerapat.b@m-society.go.th",
    phone: "055-705031 ต่อ 111",
    lineId: "arm_kpp",
    role: "member",
    status: "active",
    joinedDate: "1 ต.ค. 2024",
    avatarText: "ธบ",
  },
  {
    id: "usr_11",
    prefix: "ดร.",
    firstName: "ศรัณย์",
    lastName: "สิทธิโชค",
    name: "ดร. ศรัณย์ สิทธิโชค",
    nickname: "รัน",
    personnelType: "ที่ปรึกษา/ผู้ทรงคุณวุฒิ",
    position: "ผู้ทรงคุณวุฒิด้านสวัสดิการสังคม (คณะอนุกรรมการฟื้นฟูสมรรถภาพคนพิการ)",
    division: "คณะทำงานที่ปรึกษาและภาคีเครือข่ายภายนอก",
    department: "คณะทำงานที่ปรึกษาและภาคีเครือข่ายภายนอก",
    email: "saran.s@socialadvisor.org",
    phone: "089-854-1234",
    lineId: "dr_saran",
    role: "guest",
    status: "active",
    joinedDate: "1 ม.ค. 2025",
    avatarText: "ดศ",
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: "log_1",
    timestamp: "วันนี้ 09:15 น.",
    actor: "มะลิวัน สิทธิโยธี (Admin)",
    action: "อนุมัติแต่งตั้งบทบาท เสกพล ดิษฐโชติ เป็น Manager ฝ่ายบริหารทั่วไป",
    target: "RBAC Permission",
    status: "success",
  },
  {
    id: "log_2",
    timestamp: "เมื่อวาน 16:40 น.",
    actor: "ศรัณย์ สิทธิโชค (Guest)",
    action: "พยายามเข้าถึงโมดูล Admin Panel สิทธิ์ไม่เพียงพอ",
    target: "Access Control",
    status: "denied",
  },
  {
    id: "log_3",
    timestamp: "เมื่อวาน 14:20 น.",
    actor: "ขวัญนภา ศิริสมบัติ (Member)",
    action: "บันทึกคำขอจองห้องประชุมสุนทรภู่ผ่านระบบออนไลน์",
    target: "Meeting Booking",
    status: "success",
  },
  {
    id: "log_4",
    timestamp: "6 ต.ค. 11:00 น.",
    actor: "มะลิวัน สิทธิโยธี (Admin)",
    action: "เปิดใช้งานตารางกำหนดสิทธิ์ RBAC Module Matrix ประจำปีงบประมาณ",
    target: "System Configuration",
    status: "success",
  },
];

export const INITIAL_ACCESS_REQUESTS: AccessRequest[] = [
  {
    id: "req_1",
    prefix: "นาย",
    firstName: "พงษ์ศักดิ์",
    lastName: "รัตนวิมล",
    nickname: "บอล",
    name: "นายพงษ์ศักดิ์ รัตนวิมล",
    personnelType: "ข้าราชการ",
    position: "นักพัฒนาสังคมปฏิบัติการ",
    division: "กลุ่มนโยบายและวิชาการ",
    email: "pongsak.r@m-society.go.th",
    phone: "055-705031 ต่อ 112",
    lineId: "ball_kpp",
    requestedRole: "member",
    reason: "ขอสิทธิ์เพื่อติดตามโครงการและประสานงานข้อมูลสารสนเทศร่วมกับทีมงาน พมจ. กำแพงเพชร",
    status: "pending",
    createdAt: "วันนี้ 10:15 น.",
  },
  {
    id: "req_2",
    prefix: "นางสาว",
    firstName: "กานดา",
    lastName: "ธนโชติ",
    nickname: "กาน",
    name: "นางสาวกานดา ธนโชติ",
    personnelType: "พนักงานราชการ",
    position: "เจ้าหน้าที่ธุรการและสารบรรณ",
    division: "ฝ่ายบริหารทั่วไป",
    email: "kanda.t@m-society.go.th",
    phone: "055-705031 ต่อ 115",
    lineId: "kanda_admin",
    requestedRole: "member",
    reason: "ขอสิทธิ์เข้าใช้งานระบบจองรถยนต์สำนักงาน จองห้องประชุม และส่งเอกสารในระบบแชท",
    status: "pending",
    createdAt: "เมื่อวาน 15:30 น.",
  },
];
